sudo: false

language: node_js
node_js:
  - "4"
  - "6"
  - "8"

env:
  - ESLINT_VERSION=3
  - ESLINT_VERSION=4

cache:
  directories:
    - node_modules

before_script:
  - npm i --no-save eslint@$ESLINT_VERSION; true

after_success:
  - npm run codecov
