sudo: false

language: node_js
node_js:
  - "4"
  - "6"
  - "8"

env:
  - ESLINT_VERSION=4
  - ESLINT_VERSION=4.7

before_script:
  - npm i --no-save eslint@$ESLINT_VERSION; true

script:
  - if [ $ESLINT_VERSION = 4 ]; then npm run lint; fi
  - npm test

after_success:
  - npm run codecov
